name: Scheduled lottery

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  buy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install packages
        run: npm install --no-package-lock
        working-directory: ./

      - name: Use local action
        uses: ./src/actions/buy
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}

  redeem:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install packages
        run: npm install --no-package-lock
        working-directory: ./

      - name: Use local action
        uses: ./src/actions/redeem
